"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.runPrerenderFromAPI = runPrerenderFromAPI;
exports.runPrerenderFromCLIPrerenderCommand = runPrerenderFromCLIPrerenderCommand;
exports.runPrerenderFromAutoRun = runPrerenderFromAutoRun;
exports.runPrerender_forceExit = runPrerender_forceExit;
const utils_js_1 = require("./utils.js");
const logErrorHint_js_1 = require("../runtime/renderPage/logErrorHint.js");
const prepareViteApiCall_js_1 = require("../api/prepareViteApiCall.js");
const context_js_1 = require("../cli/context.js");
const isViteCliCall_js_1 = require("../vite/shared/isViteCliCall.js");
const runPrerender_js_1 = require("./runPrerender.js");
async function runPrerenderFromAPI(options = {}) {
    // - We purposely propagate the error to the user land, so that the error interrupts the user land. It's also, I guess, a nice-to-have that the user has control over the error.
    // - We don't use logErrorHint() because we don't have control over what happens with the error. For example, if the user land purposely swallows the error then the hint shouldn't be logged. Also, it's best if the hint is shown to the user *after* the error, but we cannot do/guarentee that.
    const { viteConfig } = await (0, runPrerender_js_1.runPrerender)(options, 'prerender()');
    return { viteConfig };
}
async function runPrerenderFromCLIPrerenderCommand() {
    try {
        const { viteConfigFromUserEnhanced } = await (0, prepareViteApiCall_js_1.prepareViteApiCall)({}, 'prerender');
        await (0, runPrerender_js_1.runPrerender)({ viteConfig: viteConfigFromUserEnhanced }, '$ vike prerender');
    }
    catch (err) {
        console.error(err);
        // Error may come from user-land; we need to use logErrorHint()
        (0, logErrorHint_js_1.logErrorHint)(err);
        process.exit(1);
    }
    runPrerender_forceExit();
    (0, utils_js_1.assert)(false);
}
async function runPrerenderFromAutoRun(viteConfig) {
    try {
        await (0, runPrerender_js_1.runPrerender)({ viteConfig }, 'auto-run');
    }
    catch (err) {
        // Avoid Rollup prefixing the error with [vike:build:pluginAutoFullBuild], see for example https://github.com/vikejs/vike/issues/472#issuecomment-1276274203
        console.error(err);
        (0, logErrorHint_js_1.logErrorHint)(err);
        process.exit(1);
    }
    const forceExit = (0, context_js_1.isVikeCli)() || (0, isViteCliCall_js_1.isViteCliCall)();
    return { forceExit };
}
function runPrerender_forceExit() {
    // Force exit; known situations where pre-rendering is hanging:
    //  - https://github.com/vikejs/vike/discussions/774#discussioncomment-5584551
    //  - https://github.com/vikejs/vike/issues/807#issuecomment-1519010902
    process.exit(0);
    /* I guess there is no need to tell the user about it? Let's see if a user complains.
     * I don't known whether there is a way to call process.exit(0) only if needed, thus I'm not sure if there is a way to conditionally show a assertInfo().
    assertInfo(false, "Pre-rendering was forced exit. (Didn't gracefully exit because the event queue isn't empty. This is usually fine, see ...", { onlyOnce: false })
    */
}
